#!/bin/bash
set -e

# create symlinks to podman and podman-mac-helper
ln -s /Applications/podman/bin/podman "$HOME"/bin/podman
ln -s /Applications/podman/bin/podman-mac-helper "$HOME"/bin/podman-mac-helper

chmod 755 "$HOME"/bin/podman "$HOME"/bin/podman-mac-helper

# create containers.conf config file to set the location of helper binaries
cat << EOF > "$HOME"/.config/containers/containers.conf
[containers]

[engine]
    helper_binaries_dir=["/Applications/podman/bin", "/Applications/podman/qemu/bin"]
[machine]

[network]

[secrets]

[configmaps]
EOF
